server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Customer Booking
          uri: http://localhost:8082
          predicates:
            - Path=/bookings/**, 
        - id: Driver Management
          uri: http://localhost:8083
          predicates:
            - Path=/drivers/**, 
        - id: Ride Management
          uri: http://localhost:8085
          predicates:
            - Path=/rides/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Customer Booking
          uri: http://customerBooking:8080
          predicates:
            - Path=/bookings/**, 
        - id: Driver Management
          uri: http://driverManagement:8080
          predicates:
            - Path=/drivers/**, 
        - id: Ride Management
          uri: http://rideManagement:8080
          predicates:
            - Path=/rides/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
