---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Customer Booking
  labels:
    app: Customer Booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customer Booking
  template:
    metadata:
      labels:
        app: Customer Booking
    spec:
      containers:
        - name: Customer Booking
          image: username/Customer Booking:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Driver Management
  labels:
    app: Driver Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Driver Management
  template:
    metadata:
      labels:
        app: Driver Management
    spec:
      containers:
        - name: Driver Management
          image: username/Driver Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Ride Management
  labels:
    app: Ride Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Ride Management
  template:
    metadata:
      labels:
        app: Ride Management
    spec:
      containers:
        - name: Ride Management
          image: username/Ride Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Customer Booking
  labels:
    app: Customer Booking
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer Booking


---


apiVersion: v1
kind: Service
metadata:
  name: Driver Management
  labels:
    app: Driver Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Driver Management


---


apiVersion: v1
kind: Service
metadata:
  name: Ride Management
  labels:
    app: Ride Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Ride Management

